nelmio_api_doc:
    documentation:
        info:
            title: Template backend JWT API
            description: Template backend API's routes
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!_).* # Exclude routes starting with _